# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1232f4649984764ac8b46d1d81fac3637df68ddc9746a0182e23d60fa8d2dc97a8ea508eb36d1bccc28e062c73ecc9a0332cbdf1f828409307d2b5c555f691f

test:
  secret_key_base: 275c7bc34fda69d41414bff82bc985724bfba805034e09f7529afd1c68bc0e2c9d221e09bb4a6f984ab84b385ad3ddf204cde68b8ce0ffa943c3de47580fb316

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
